[package]
name = "type-globe"
version = "0.1.0"
edition = "2021"
authors = ["kako-jun"]
description = "A quiz and typing game that combines learning with skill improvement"
license = "MIT"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
